from django.conf.urls.defaults import *

urlpatterns = patterns("",
    url(r"^$", "domains.views.domains", name="domain_list"),
    url(r"^check/$", "domains.views.check", name="check_domain"),
    url(r"^(?P<domain_id>\d+)/customize/$", "domains.views.customize", name="customize_domain"),
    url(r"^(?P<domain_id>\d+)/verify/$", "domains.views.verify", name="verify_domain"),
    url(r"^beforeverify/$", "domains.views.before_verify", name="before_verify"),
    url(r"^(?P<domain_id>\d+)/uploads_badge/$",
        "domains.views.upload_badge",name="upload_badge"),
    url(r"^(?P<domain_id>\d+)/badge/complete/$", "domains.views.complete_badge",
        name="complete_badge"),
    url(r"^offsetco2/$", "domains.views.offset_co2", name="offset_co2"),
    url(r"^customize/$", "domains.views.customize", name="customize_domain"),
    url(r"^(?P<log_id>\d+)/co2display/$", "domains.views.co2_display", name="co2_display"),
    url(r"^notapproved/$", "domains.views.not_approved", name="not_approved"),
    url(r"^painlessmigrate/$", "domains.views.painless_migrate", name="painless_approved"),
    url(r"^certifiedhosts/$", "domains.views.certified_hosts", name="certified_hosts"),
    url(r"^(?P<domain_id>\d+)/modify/$", "domains.views.modify_domain", name="modify_domain"),
    url(r"^(?P<domain_id>\d+)/delete/$", "domains.views.delete_domain", name="delete_domain"),
    url(r"^(?P<domain_id>\d+)/verify_meta/$", "domains.views.verify_meta", name="verify_meta"),
    url(r"^(?P<domain_id>\d+)/certificate/$", "domains.views.certificate", name="certificate"),
    url(r"^process/$", "domains.views.process", name="process_domain"),
    url(r"^index/$", "domains.views.index", name="index_domain"),
    url(r"^downloadhtml/$", "domains.views.download_html_file", 
        name="download_html"),
)